name: illuminator-examples
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - illuminator
    - jupyterlab
    # For testing
    - pytest
    - nbclient
    - nbformat
    - pandas
    - numpy
