name: Test Examples

on:
  push:
    branches: [ "main", "dev", "develop"]
  pull_request:
    branches: [ "main", "dev", "develop"]

jobs:
  test-examples:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Miniconda
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          # optional: specify Python version for conda itself
          python-version: 3.14

      # Remove environment if it exists
      - name: Remove old conda environment
        run: conda env remove -n illuminator-examples || true

      # Create conda environment from environment.yml
      - name: Create conda environment
        run: conda env create -n illuminator-examples -f environment.yml

      # Activate environment and run tests
      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate illuminator-examples
          pytest -v
